<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
        <a href="<?php echo $block->getBaseUrl(); ?>blog/index/create"
         class="btn btn-primary btn-xs pull-right" style="border: 1px solid black; padding: 5px 10px;">
         Create New Post
        </a>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Url Key</td>
            <td>Image</td>
            <td>Content</td>
            <td>Status</td>
            <td>Created At</td>
            <td>Updated At</td>
        </tr>
    </thead>

    <tbody>
        <?php
        $posts = $block->getPosts();

        foreach ($posts as $post) :
        ?>
            <tr style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                <td><?php echo $post->getId(); ?></td>
                <td><?php echo $post->getName(); ?></td>
                <td><?php echo $post->getUrlKey(); ?></td>
                <td><?php echo $post->getImage(); ?></td>
                <td><?php echo $post->getContent(); ?></td>
                <td><?php echo $post->getStatus(); ?></td>
                <td><?php echo $post->getCreatedAt(); ?></td>
                <td><?php echo $post->getUpdatedAt(); ?></td>
                <td>
                    <a href="<?php echo $block->getBaseUrl(); ?>blog/index/edit/post_id/<?php echo $post->getId(); ?>">Edit</a>
                </td>
                <td>
                    <a href="<?php echo $block->getBaseUrl(); ?>blog/index/delete/post_id/<?php echo $post->getId(); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>